# SPDX-FileCopyrightText: 2025 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT

name: Build iOS WebRTC

on:
  workflow_dispatch:
    inputs:
      webrtc-branch:
        description: 'WebRTC branch (numeric)'
        required: true
        type: number

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build iOS WebRTC lib - Branch ${{ github.event.inputs.webrtc-branch }}
    runs-on: macos-15

    steps:
    - name: Checkout app
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        path: repo

    - name: Setup depot tools
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        readlink -f depot_tools >> $GITHUB_PATH

    - name: Link python
      run: sudo ln -s /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /usr/local/bin/python

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
      with:
        xcode-version: '26.1.1'

#    - name: Install iOS 26.1
#      run: |
#        xcrun simctl list > /dev/null # Required to prevent the next command from sometimes not working
#        # xcodebuild -downloadPlatform iOS -buildVersion 26.1

    - name: Build iOS WebRTC lib - Branch ${{ github.event.inputs.webrtc-branch }}
      run: |
        mkdir webrtc_ios && cd webrtc_ios
        fetch --nohooks webrtc_ios
        gclient sync
        cd src
        git checkout -b branch_${{ github.event.inputs.webrtc-branch }} branch-heads/${{ github.event.inputs.webrtc-branch }}
        gclient sync -D --no-history

        echo "Applying patches..."
        pwd
        echo ${{ github.workspace }}
        ls -ahl ${{ github.workspace }}/repo/ios/patches/*.patch
        find ${{ github.workspace }}/repo/ios/patches/ -name "*.patch" -print0 | xargs -0 -n 1 patch -p1 -i

        echo "Building..."
        cd tools_webrtc/ios
        python build_ios_libs.py

    # Create a zip file here as the ones created by the artifact step might be rejected by Xcode
    - name: Zip & generate checksum
      run: |
        cd webrtc_ios/src/out_ios_libs/
        zip -r WebRTC-${{ github.event.inputs.webrtc-branch }}.xcframework.zip WebRTC.xcframework
        echo "## iOS WebRTC lib - Branch ${{ github.event.inputs.webrtc-branch }}" >> $GITHUB_STEP_SUMMARY
        echo "Swift checksum: $(swift package compute-checksum WebRTC-${{ github.event.inputs.webrtc-branch }}.xcframework.zip)" >> $GITHUB_STEP_SUMMARY

    - name: Upload build
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        path: webrtc_ios/src/out_ios_libs/WebRTC-${{ github.event.inputs.webrtc-branch }}.xcframework.zip
        archive: false
        retention-days: 4
